/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author stephancedillo
 */
public class BuscarPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form buscarLibroView
     */
    public BuscarPrestamoView() {
        initComponents();
    }

    public JButton getBtnCedula() {
        return btnCedula;
    }

    public JButton getBtnID() {
        return btnID;
    }

    public JButton getBtnISBN() {
        return btnISBN;
    }

    public JLabel getLblEstado() {
        return lblEstado2;
    }

    public JPanel getPnlEstadoDevuelto() {
        return pnlEstadoDevuelto;
    }

    public JTable getTblLibrosBuscados() {
        return tblLibrosBuscados;
    }

    public JTextField getTxtCedulaBuscado() {
        return txtCedulaBuscado;
    }

    public JTextField getTxtFechaDevueltoBuscado() {
        return txtFechaDevueltoBuscado;
    }

    public JTextField getTxtFechaPedidoBuscado() {
        return txtFechaPedidoBuscado;
    }

    public JTextField getTxtGmailBuscado() {
        return txtGmailBuscado;
    }

    public JTextField getTxtICedula() {
        return txtICedula;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtISBN() {
        return txtISBN;
    }

    public JTextField getTxtNombreBuscado() {
        return txtNombreBuscado;
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloBusquedaPrestamo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblISBN3 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCedula2 = new javax.swing.JLabel();
        txtICedula = new javax.swing.JTextField();
        btnID = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCedulaBuscado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblFechaPedido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtGmailBuscado = new javax.swing.JTextField();
        lblCedula3 = new javax.swing.JLabel();
        lblFechaDevuelto = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        pnlEstadoDevuelto = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosBuscados = new javax.swing.JTable();
        txtFechaPedidoBuscado = new javax.swing.JTextField();
        txtFechaDevueltoBuscado = new javax.swing.JTextField();
        txtNombreBuscado = new javax.swing.JTextField();
        btnISBN = new javax.swing.JButton();
        btnCedula = new javax.swing.JButton();
        lblBuscarPor = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(240, 237, 237));

        lblTituloBusquedaPrestamo.setFont(new java.awt.Font("ITF Devanagari", 1, 24)); // NOI18N
        lblTituloBusquedaPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloBusquedaPrestamo.setText("BUSQUEDA PRESTAMO");

        jPanel2.setBackground(new java.awt.Color(249, 245, 245));

        lblISBN3.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblISBN3.setForeground(new java.awt.Color(0, 0, 0));
        lblISBN3.setText("ISBN:");

        lblID.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("Id:");

        lblCedula2.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblCedula2.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula2.setText("Cedula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblISBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtICedula, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblISBN3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnID.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnID.setText("ID");

        jPanel3.setBackground(new java.awt.Color(249, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCedulaBuscado.setEditable(false);
        txtCedulaBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 13)); // NOI18N
        txtCedulaBuscado.addActionListener(this::txtCedulaBuscadoActionPerformed);

        jLabel4.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("001");

        lblEmail2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail2.setText("Email:");

        lblFechaPedido.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblFechaPedido.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaPedido.setText("Fecha Pedido:");

        lblNombre.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre:");

        txtGmailBuscado.setEditable(false);
        txtGmailBuscado.addActionListener(this::txtGmailBuscadoActionPerformed);

        lblCedula3.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblCedula3.setForeground(new java.awt.Color(51, 51, 51));
        lblCedula3.setText("Cedula:");

        lblFechaDevuelto.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblFechaDevuelto.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaDevuelto.setText("Fecha Devuelto");

        lblEstado2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEstado2.setForeground(new java.awt.Color(51, 51, 51));
        lblEstado2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado2.setText("Estado:");

        pnlEstadoDevuelto.setBackground(new java.awt.Color(0, 255, 0));
        pnlEstadoDevuelto.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout pnlEstadoDevueltoLayout = new javax.swing.GroupLayout(pnlEstadoDevuelto);
        pnlEstadoDevuelto.setLayout(pnlEstadoDevueltoLayout);
        pnlEstadoDevueltoLayout.setHorizontalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        pnlEstadoDevueltoLayout.setVerticalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        lblID2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblID2.setForeground(new java.awt.Color(51, 51, 51));
        lblID2.setText("ID:");

        tblLibrosBuscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ISBN", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosBuscados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFechaPedidoBuscado.setEditable(false);
        txtFechaPedidoBuscado.addActionListener(this::txtFechaPedidoBuscadoActionPerformed);

        txtFechaDevueltoBuscado.setEditable(false);
        txtFechaDevueltoBuscado.addActionListener(this::txtFechaDevueltoBuscadoActionPerformed);

        txtNombreBuscado.setEditable(false);
        txtNombreBuscado.addActionListener(this::txtNombreBuscadoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblID2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCedula3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtNombreBuscado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail2))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaDevuelto)
                            .addComponent(lblFechaPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtFechaDevueltoBuscado))
                        .addContainerGap(36, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblID2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula3)
                    .addComponent(lblEmail2)
                    .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPedido)
                    .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDevuelto)
                    .addComponent(lblNombre)
                    .addComponent(txtFechaDevueltoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnISBN.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnISBN.setText("ISBN");

        btnCedula.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnCedula.setText("CEDULA");

        lblBuscarPor.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblBuscarPor.setForeground(new java.awt.Color(51, 51, 51));
        lblBuscarPor.setText("BUSCAR POR :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloBusquedaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblBuscarPor)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTituloBusquedaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscarPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnID)
                    .addComponent(btnISBN)
                    .addComponent(btnCedula))
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGmailBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGmailBuscadoActionPerformed

    private void txtCedulaBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscadoActionPerformed

    private void txtFechaPedidoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPedidoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPedidoBuscadoActionPerformed

    private void txtFechaDevueltoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDevueltoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDevueltoBuscadoActionPerformed

    private void txtNombreBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCedula;
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnISBN;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarPor;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblCedula3;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblFechaDevuelto;
    private javax.swing.JLabel lblFechaPedido;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblISBN3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTituloBusquedaPrestamo;
    private javax.swing.JPanel pnlEstadoDevuelto;
    private javax.swing.JTable tblLibrosBuscados;
    private javax.swing.JTextField txtCedulaBuscado;
    private javax.swing.JTextField txtFechaDevueltoBuscado;
    private javax.swing.JTextField txtFechaPedidoBuscado;
    private javax.swing.JTextField txtGmailBuscado;
    private javax.swing.JTextField txtICedula;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNombreBuscado;
    // End of variables declaration//GEN-END:variables
}
