/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author stephancedillo
 */
public class buscarUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form buscarLibroView
     */
    public buscarUsuarioView() {
        initComponents();
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public JLabel getLblDireccion() {
        return lblDireccion;
    }

    public JLabel getLblDiscapacidad() {
        return lblDiscapacidad;
    }

    public JLabel getLblEdad() {
        return lblEdad;
    }

    public JLabel getLblEmail() {
        return lblEmail;
    }

    public JLabel getLblFechaCaducidad() {
        return lblFechaCaducidad;
    }

    public JLabel getLblIdioma() {
        return lblIdioma;
    }

    public JLabel getLblMembresia() {
        return lblMembresia;
    }

    public JLabel getLblTituloBuscado() {
        return lblTituloBuscado;
    }

    public JLabel getLblTituloBusquedaUsuario() {
        return lblTituloBusquedaUsuario;
    }

    public JPanel getPnlEstadoDiscapacidadBuscado() {
        return pnlEstadoDiscapacidadBuscado;
    }

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public JTextField getTxtDireccionBuscado() {
        return txtDireccionBuscado;
    }

    public JTextField getTxtEdadBuscado() {
        return txtEdadBuscado;
    }

    public JTextField getTxtEmailBuscado() {
        return txtEmailBuscado;
    }

    public JFormattedTextField getTxtFormatedFechaCaducidadBuscado() {
        return txtFormatedFechaCaducidadBuscado;
    }

    public JTextField getTxtIdiomaBuscado() {
        return txtIdiomaBuscado;
    }

    public JTextField getTxtMembresiaBuscado() {
        return txtMembresiaBuscado;
    }

     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloBusquedaUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmailBuscado = new javax.swing.JTextField();
        lblTituloBuscado = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblFechaCaducidad = new javax.swing.JLabel();
        txtDireccionBuscado = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtEdadBuscado = new javax.swing.JTextField();
        lblIdioma = new javax.swing.JLabel();
        txtIdiomaBuscado = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        txtMembresiaBuscado = new javax.swing.JTextField();
        lblDiscapacidad = new javax.swing.JLabel();
        pnlEstadoDiscapacidadBuscado = new javax.swing.JPanel();
        txtFormatedFechaCaducidadBuscado = new javax.swing.JFormattedTextField();

        jPanel1.setBackground(new java.awt.Color(240, 237, 237));

        lblTituloBusquedaUsuario.setFont(new java.awt.Font("ITF Devanagari", 1, 24)); // NOI18N
        lblTituloBusquedaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloBusquedaUsuario.setText("BUSQUEDA USUARIO");

        jPanel2.setBackground(new java.awt.Color(249, 245, 245));

        lblCedula.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cedula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnBuscar.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR ");

        jPanel3.setBackground(new java.awt.Color(249, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibroBuscar.png"))); // NOI18N

        txtEmailBuscado.setEditable(false);
        txtEmailBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 13)); // NOI18N

        lblTituloBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        lblTituloBuscado.setForeground(new java.awt.Color(51, 51, 51));
        lblTituloBuscado.setText("Titulo");

        lblEdad.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(51, 51, 51));
        lblEdad.setText("Edad:");

        lblFechaCaducidad.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblFechaCaducidad.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaCaducidad.setText("Caduca en:");

        txtDireccionBuscado.setEditable(false);

        lblDireccion.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblDireccion.setForeground(new java.awt.Color(51, 51, 51));
        lblDireccion.setText("Direccion:");

        txtEdadBuscado.setEditable(false);
        txtEdadBuscado.addActionListener(this::txtEdadBuscadoActionPerformed);

        lblIdioma.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblIdioma.setForeground(new java.awt.Color(51, 51, 51));
        lblIdioma.setText("Idioma:");

        txtIdiomaBuscado.setEditable(false);

        lblEmail.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Email:");

        lblMembresia.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblMembresia.setForeground(new java.awt.Color(51, 51, 51));
        lblMembresia.setText("Membresia:");

        txtMembresiaBuscado.setEditable(false);

        lblDiscapacidad.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblDiscapacidad.setForeground(new java.awt.Color(51, 51, 51));
        lblDiscapacidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDiscapacidad.setText("Discapacidad");

        pnlEstadoDiscapacidadBuscado.setBackground(new java.awt.Color(0, 255, 0));
        pnlEstadoDiscapacidadBuscado.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout pnlEstadoDiscapacidadBuscadoLayout = new javax.swing.GroupLayout(pnlEstadoDiscapacidadBuscado);
        pnlEstadoDiscapacidadBuscado.setLayout(pnlEstadoDiscapacidadBuscadoLayout);
        pnlEstadoDiscapacidadBuscadoLayout.setHorizontalGroup(
            pnlEstadoDiscapacidadBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        pnlEstadoDiscapacidadBuscadoLayout.setVerticalGroup(
            pnlEstadoDiscapacidadBuscadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        txtFormatedFechaCaducidadBuscado.setEditable(false);
        txtFormatedFechaCaducidadBuscado.addActionListener(this::txtFormatedFechaCaducidadBuscadoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdiomaBuscado))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTituloBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblEdad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEdadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblDireccion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDireccionBuscado))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblMembresia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMembresiaBuscado))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblFechaCaducidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFormatedFechaCaducidadBuscado))
                    .addComponent(pnlEstadoDiscapacidadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTituloBuscado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaCaducidad)
                    .addComponent(lblEmail)
                    .addComponent(txtFormatedFechaCaducidadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdad)
                    .addComponent(txtEdadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMembresia)
                    .addComponent(txtMembresiaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccionBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiscapacidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEstadoDiscapacidadBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdioma)
                            .addComponent(txtIdiomaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTituloBusquedaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTituloBusquedaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEdadBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadBuscadoActionPerformed

    private void txtFormatedFechaCaducidadBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFormatedFechaCaducidadBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFormatedFechaCaducidadBuscadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDiscapacidad;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaCaducidad;
    private javax.swing.JLabel lblIdioma;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblTituloBuscado;
    private javax.swing.JLabel lblTituloBusquedaUsuario;
    private javax.swing.JPanel pnlEstadoDiscapacidadBuscado;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccionBuscado;
    private javax.swing.JTextField txtEdadBuscado;
    private javax.swing.JTextField txtEmailBuscado;
    private javax.swing.JFormattedTextField txtFormatedFechaCaducidadBuscado;
    private javax.swing.JTextField txtIdiomaBuscado;
    private javax.swing.JTextField txtMembresiaBuscado;
    // End of variables declaration//GEN-END:variables
}
