/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author stephancedillo
 */
public class DevolucionPrestamoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form buscarLibroView
     */
    public DevolucionPrestamoView() {
        initComponents();

        
    }

    public JLabel getLblCedula() {
        return lblCedula;
    }

    public JLabel getLblCedula2() {
        return lblCedula2;
    }

    public JLabel getLblDevuelto() {
        return lblDevuelto;
    }

    public JLabel getLblGmail() {
        return lblGmail;
    }

    public JLabel getLblID() {
        return lblID;
    }

    public JLabel getLblID2() {
        return lblID2;
    }

    public JLabel getLblISBN() {
        return lblISBN;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JLabel getLblPedido() {
        return lblPedido;
    }

    public JLabel getLblTItuloDevolucionPrestamo() {
        return lblTItuloDevolucionPrestamo;
    }

    public JLabel getLblTextoPorBuscar() {
        return lblTextoPorBuscar;
    }
    
    

    public JLabel getLblIDBuscado() {
        return lblIDBuscado;
    }
    
    

    public JButton getBtnCedula() {
        return btnCedula;
    }

    public JButton getBtnDevolucion() {
        return btnDevolucion;
    }

    public JButton getBtnID() {
        return btnID;
    }

    public JButton getBtnISBN() {
        return btnISBN;
    }

    public JLabel getLblEstado() {
        return lblEstado;
    }

    public JPanel getPnlEstadoDevuelto() {
        return pnlEstadoDevuelto;
    }

    public JTable getTblLibrosBuscados() {
        return tblLibrosBuscados;
    }

    public JTextField getTxtCedulaBuscado() {
        return txtCedulaBuscado;
    }

    public JTextField getTxtFechaDevueltoBuscado() {
        return txtFechaDevueltoBuscado;
    }

    public JTextField getTxtFechaPedidoBuscado() {
        return txtFechaPedidoBuscado;
    }

    public JTextField getTxtGmailBuscado() {
        return txtGmailBuscado;
    }

    public JTextField getTxtICedula() {
        return txtICedula;
    }

    public JTextField getTxtID() {
        return txtID;
    }

    public JTextField getTxtISBN() {
        return txtISBN;
    }

    public JTextField getTxtNombreBuscado() {
        return txtNombreBuscado;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTItuloDevolucionPrestamo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblISBN = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCedula = new javax.swing.JLabel();
        txtICedula = new javax.swing.JTextField();
        btnID = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtCedulaBuscado = new javax.swing.JTextField();
        lblIDBuscado = new javax.swing.JLabel();
        lblGmail = new javax.swing.JLabel();
        lblPedido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtGmailBuscado = new javax.swing.JTextField();
        lblCedula2 = new javax.swing.JLabel();
        lblDevuelto = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        pnlEstadoDevuelto = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosBuscados = new javax.swing.JTable();
        txtFechaPedidoBuscado = new javax.swing.JTextField();
        txtFechaDevueltoBuscado = new javax.swing.JTextField();
        txtNombreBuscado = new javax.swing.JTextField();
        btnISBN = new javax.swing.JButton();
        btnDevolucion = new javax.swing.JButton();
        lblTextoPorBuscar = new javax.swing.JLabel();
        btnCedula = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(240, 237, 237));

        lblTItuloDevolucionPrestamo.setFont(new java.awt.Font("ITF Devanagari", 1, 24)); // NOI18N
        lblTItuloDevolucionPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        lblTItuloDevolucionPrestamo.setText("DEVOLUCION DE PRESTAMO");

        jPanel2.setBackground(new java.awt.Color(249, 245, 245));

        lblISBN.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblISBN.setForeground(new java.awt.Color(0, 0, 0));
        lblISBN.setText("ISBN:");

        lblID.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 0));
        lblID.setText("Id:");

        lblCedula.setFont(new java.awt.Font("ITF Devanagari", 1, 18)); // NOI18N
        lblCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblCedula.setText("Cedula:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtICedula, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        btnID.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnID.setText("ID");

        jPanel3.setBackground(new java.awt.Color(249, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCedulaBuscado.setEditable(false);
        txtCedulaBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 13)); // NOI18N
        txtCedulaBuscado.addActionListener(this::txtCedulaBuscadoActionPerformed);

        lblIDBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        lblIDBuscado.setForeground(new java.awt.Color(51, 51, 51));
        lblIDBuscado.setText("001");

        lblGmail.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblGmail.setForeground(new java.awt.Color(51, 51, 51));
        lblGmail.setText("Gmail:");

        lblPedido.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblPedido.setForeground(new java.awt.Color(51, 51, 51));
        lblPedido.setText("Fecha Pedido:");

        lblNombre.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre:");

        txtGmailBuscado.setEditable(false);
        txtGmailBuscado.addActionListener(this::txtGmailBuscadoActionPerformed);

        lblCedula2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblCedula2.setForeground(new java.awt.Color(51, 51, 51));
        lblCedula2.setText("Cedula:");

        lblDevuelto.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblDevuelto.setForeground(new java.awt.Color(51, 51, 51));
        lblDevuelto.setText("Fecha Devuelto");

        lblEstado.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(51, 51, 51));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");

        pnlEstadoDevuelto.setBackground(new java.awt.Color(0, 255, 0));
        pnlEstadoDevuelto.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout pnlEstadoDevueltoLayout = new javax.swing.GroupLayout(pnlEstadoDevuelto);
        pnlEstadoDevuelto.setLayout(pnlEstadoDevueltoLayout);
        pnlEstadoDevueltoLayout.setHorizontalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        pnlEstadoDevueltoLayout.setVerticalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        lblID2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblID2.setForeground(new java.awt.Color(51, 51, 51));
        lblID2.setText("ID:");

        tblLibrosBuscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ISBN", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosBuscados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFechaPedidoBuscado.setEditable(false);
        txtFechaPedidoBuscado.addActionListener(this::txtFechaPedidoBuscadoActionPerformed);

        txtFechaDevueltoBuscado.setEditable(false);
        txtFechaDevueltoBuscado.addActionListener(this::txtFechaDevueltoBuscadoActionPerformed);

        txtNombreBuscado.setEditable(false);
        txtNombreBuscado.addActionListener(this::txtNombreBuscadoActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblID2)
                .addGap(18, 18, 18)
                .addComponent(lblIDBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCedula2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtNombreBuscado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGmail))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(228, 228, 228)
                            .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPedido)
                            .addComponent(lblDevuelto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(txtFechaDevueltoBuscado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDBuscado)
                    .addComponent(lblID2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedula2)
                        .addComponent(lblGmail)
                        .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPedido)
                        .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDevuelto)
                    .addComponent(lblNombre)
                    .addComponent(txtFechaDevueltoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnISBN.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnISBN.setText("ISBN");

        btnDevolucion.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnDevolucion.setText("DEVOLUCIÓN");

        lblTextoPorBuscar.setFont(new java.awt.Font("ITF Devanagari", 1, 14)); // NOI18N
        lblTextoPorBuscar.setForeground(new java.awt.Color(51, 51, 51));
        lblTextoPorBuscar.setText("BUSCAR POR :");

        btnCedula.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        btnCedula.setText("CEDULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTItuloDevolucionPrestamo)
                .addGap(164, 164, 164))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTextoPorBuscar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnID, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                            .addComponent(btnISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnDevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTItuloDevolucionPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoPorBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnID)
                    .addComponent(btnISBN)
                    .addComponent(btnCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDevolucion)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGmailBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGmailBuscadoActionPerformed

    private void txtCedulaBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscadoActionPerformed

    private void txtFechaPedidoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPedidoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPedidoBuscadoActionPerformed

    private void txtFechaDevueltoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDevueltoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDevueltoBuscadoActionPerformed

    private void txtNombreBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCedula;
    private javax.swing.JButton btnDevolucion;
    private javax.swing.JButton btnID;
    private javax.swing.JButton btnISBN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula2;
    private javax.swing.JLabel lblDevuelto;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblIDBuscado;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblTItuloDevolucionPrestamo;
    private javax.swing.JLabel lblTextoPorBuscar;
    private javax.swing.JPanel pnlEstadoDevuelto;
    private javax.swing.JTable tblLibrosBuscados;
    private javax.swing.JTextField txtCedulaBuscado;
    private javax.swing.JTextField txtFechaDevueltoBuscado;
    private javax.swing.JTextField txtFechaPedidoBuscado;
    private javax.swing.JTextField txtGmailBuscado;
    private javax.swing.JTextField txtICedula;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtNombreBuscado;
    // End of variables declaration//GEN-END:variables
}
