/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import ups.edu.ec.bibleotecainterfaz.models.Usuario;

/**
 *
 * @author ASUS
 */
public class ListarUsuarioView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    
    public DefaultTableModel getModelo() {
        return modelo;
       
    }

    /**
     * 
     * Creates new form ListarUsuarioView
     */
    public void setModelo(DefaultTableModel modelo) {    
        this.modelo = modelo;
    }

    public ListarUsuarioView() {
        initComponents();
        configurarTabla();
    }

    public JButton getBtnListarUsuario() {
        return btnListarUsuario;
    }

    public JTable getTblListarUsuario() {
        return tblListarUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarUsuario = new javax.swing.JTable();
        btnListarUsuario = new javax.swing.JButton();

        setClosable(true);

        tblListarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListarUsuario);

        btnListarUsuario.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(btnListarUsuario)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarUsuario;
    // End of variables declaration//GEN-END:variables
  private void configurarTabla() {
        String[] columnas = {"Nombre", "Email", "Edad", "Direccion", "Membresia", "Caduca en"};
        modelo = new DefaultTableModel(columnas, 0);

        tblListarUsuario.setModel(modelo);
        tblListarUsuario.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblListarUsuario.getColumnModel().getColumn(1).setPreferredWidth(350);
        tblListarUsuario.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblListarUsuario.getColumnModel().getColumn(3).setPreferredWidth(270);
        tblListarUsuario.getColumnModel().getColumn(4).setPreferredWidth(300);
        tblListarUsuario.getColumnModel().getColumn(5).setPreferredWidth(300);
        tblListarUsuario.getColumnModel().getColumn(6).setPreferredWidth(300);
    }

    public void cargarDatos(List<Usuario> usuarios) {
        modelo.setRowCount(0);

        for (Usuario usuario : usuarios) {
            Object[] fila = {
                usuario.getNombre(),
                usuario.getEmail(),
                usuario.getEdad(),
                usuario.getDireccion(),
                usuario.getMembresia().getTipoMembresia(),
                usuario.getMembresia().getFechaVencimiento(),

            };
            modelo.addRow(fila);
        }
    }
}
