/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import ups.edu.ec.bibleotecainterfaz.models.Usuario;

/**
 *
 * @author ASUS
 */
public class ListarUsuarioView extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
    /**
     * Creates new form ListarUsuarioView
     */
    public ListarUsuarioView() {
        initComponents();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarUsuario = new javax.swing.JTable();
        btnListarUsuario = new javax.swing.JButton();

        tblListarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListarUsuario);

        btnListarUsuario.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnListarUsuario)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addComponent(btnListarUsuario)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarUsuario;
    // End of variables declaration//GEN-END:variables
  private void configurarTabla() {
       String[] columnas = {"Nombre","Gmail", "Edad", "Direccion","Membresia","Caduca en","Discapacidad"};
        modelo = new DefaultTableModel(columnas, 0);
        
        tblListarUsuario.setModel(modelo);
    }
    
//    public void cargarDatos(List<Usuario> usuarios){
//        modelo.setRowCount(0);
//        for (Usuario usuario : usuarios) {
//            Object[] fila = {
//                usuario.getNombre(),
//                usuario.getEmail(),
//                usuario.getEdad(),
//                usuario.getDireccion(),
//                usuario.getMembresia(),
//                usuario.getMembresia().getFechaVencimiento(),
//                usuario.isTieneDiscapacidad()};
//            modelo.addRow(fila);
//        }
//        
//    }

}
