/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import java.util.List;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import ups.edu.ec.bibleotecainterfaz.models.Libro;

/**
 *
 * @author ASUS
 */
public class ListarLibroView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    /**
     * Creates new form ListarLibroView
     */
    public ListarLibroView() {
        initComponents();
        configurarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarLibro = new javax.swing.JTable();
        btnListarLibro = new javax.swing.JButton();

        tblListarLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListarLibro);

        btnListarLibro.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListarLibro)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarLibro)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnListarLibro() {
        return btnListarLibro;
    }

    public JTable getTblListarLibro() {
        return tblListarLibro;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListarLibro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarLibro;
    // End of variables declaration//GEN-END:variables
private void configurarTabla() {
        String[] columnas = {"Nombre", "ISBN", "Autor", "+18", "Genero", "Idioma"};
        modelo = new DefaultTableModel(columnas, 0);

        tblListarLibro.setModel(modelo);
    }

    public void cargarDatos(List<Libro> libros) {
        modelo.setRowCount(0);

        for (Libro libro : libros) {
            Object[] fila = {
                libro.getNombre(),
                libro.getISBN(),
                libro.getAutor(),
                libro.isSirestriccionEdad(),
                libro.getGenero(),
                libro.getIdioma()
            };
            modelo.addRow(fila);
        }
    }
}
