/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author stephancedillo
 */
public class PrestamoView extends javax.swing.JPanel {

    /**
     * Creates new form PrestamoView
     */
    public PrestamoView() {
        initComponents();
    }

    public JLabel getLblCedula3() {
        return lblCedula3;
    }

    public JLabel getLblEmail2() {
        return lblEmail2;
    }

    public JLabel getLblEstado2() {
        return lblEstado2;
    }

    public JLabel getLblFechaDevuelto() {
        return lblFechaDevuelto;
    }

    public JLabel getLblFechaPedido() {
        return lblFechaPedido;
    }

    public JLabel getLblID2() {
        return lblID2;
    }

    public JLabel getLblIDBuscado() {
        return lblIDBuscado;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public JPanel getPnlEstadoDevuelto() {
        return pnlEstadoDevuelto;
    }

    public JTable getTblLibrosBuscados() {
        return tblLibrosBuscados;
    }

    public JTextField getTxtCedulaBuscado() {
        return txtCedulaBuscado;
    }

    public JTextField getTxtFechaDevueltoBuscado() {
        return txtFechaDevueltoBuscado;
    }

    public JTextField getTxtFechaPedidoBuscado() {
        return txtFechaPedidoBuscado;
    }

    public JTextField getTxtGmailBuscado() {
        return txtGmailBuscado;
    }

    public JTextField getTxtNombreBuscado() {
        return txtNombreBuscado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtCedulaBuscado = new javax.swing.JTextField();
        lblIDBuscado = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        lblFechaPedido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtGmailBuscado = new javax.swing.JTextField();
        lblCedula3 = new javax.swing.JLabel();
        lblFechaDevuelto = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        pnlEstadoDevuelto = new javax.swing.JPanel();
        lblID2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosBuscados = new javax.swing.JTable();
        txtFechaPedidoBuscado = new javax.swing.JTextField();
        txtFechaDevueltoBuscado = new javax.swing.JTextField();
        txtNombreBuscado = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(249, 245, 245));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtCedulaBuscado.setEditable(false);
        txtCedulaBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 13)); // NOI18N

        lblIDBuscado.setFont(new java.awt.Font("ITF Devanagari", 0, 18)); // NOI18N
        lblIDBuscado.setForeground(new java.awt.Color(51, 51, 51));
        lblIDBuscado.setText("001");

        lblEmail2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail2.setText("Email:");

        lblFechaPedido.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblFechaPedido.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaPedido.setText("Fecha Pedido:");

        lblNombre.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Nombre:");

        txtGmailBuscado.setEditable(false);

        lblCedula3.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblCedula3.setForeground(new java.awt.Color(51, 51, 51));
        lblCedula3.setText("Cedula:");

        lblFechaDevuelto.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblFechaDevuelto.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaDevuelto.setText("Fecha Devolucion");

        lblEstado2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblEstado2.setForeground(new java.awt.Color(51, 51, 51));
        lblEstado2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado2.setText("Estado:");

        pnlEstadoDevuelto.setBackground(new java.awt.Color(0, 255, 0));
        pnlEstadoDevuelto.setForeground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout pnlEstadoDevueltoLayout = new javax.swing.GroupLayout(pnlEstadoDevuelto);
        pnlEstadoDevuelto.setLayout(pnlEstadoDevueltoLayout);
        pnlEstadoDevueltoLayout.setHorizontalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        pnlEstadoDevueltoLayout.setVerticalGroup(
            pnlEstadoDevueltoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        lblID2.setFont(new java.awt.Font("ITF Devanagari", 0, 14)); // NOI18N
        lblID2.setForeground(new java.awt.Color(51, 51, 51));
        lblID2.setText("ID:");

        tblLibrosBuscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ISBN", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosBuscados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtFechaPedidoBuscado.setEditable(false);

        txtFechaDevueltoBuscado.setEditable(false);

        txtNombreBuscado.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblID2)
                        .addGap(18, 18, 18)
                        .addComponent(lblIDBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                            .addComponent(txtNombreBuscado))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblEmail2))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblCedula3)
                                .addGap(188, 188, 188)
                                .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaDevuelto)
                                    .addComponent(lblFechaPedido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(txtFechaDevueltoBuscado)))
                            .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDBuscado)
                    .addComponent(lblID2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula3)
                    .addComponent(lblEmail2)
                    .addComponent(txtGmailBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaPedido)
                    .addComponent(txtFechaPedidoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDevuelto)
                    .addComponent(lblNombre)
                    .addComponent(txtFechaDevueltoBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblEstado2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEstadoDevuelto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 271, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedula3;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblFechaDevuelto;
    private javax.swing.JLabel lblFechaPedido;
    private javax.swing.JLabel lblID2;
    private javax.swing.JLabel lblIDBuscado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlEstadoDevuelto;
    private javax.swing.JTable tblLibrosBuscados;
    private javax.swing.JTextField txtCedulaBuscado;
    private javax.swing.JTextField txtFechaDevueltoBuscado;
    private javax.swing.JTextField txtFechaPedidoBuscado;
    private javax.swing.JTextField txtGmailBuscado;
    private javax.swing.JTextField txtNombreBuscado;
    // End of variables declaration//GEN-END:variables
}
