/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ups.edu.ec.bibleotecainterfaz.view;

import ups.edu.ec.bibleotecainterfaz.view.*;

/**
 *
 * @author stephancedillo
 */
public class PrincipalView extends javax.swing.JFrame {

    //======= LIBRO =========
    private CrearLibroView crearLibroView;
    private ActualizarLibroView actualizarLibroView;
    private EliminarLibroView eliminarLibroView;
    private BuscarLibroView buscarLibroView;
    private ListarLibroView listarLibroView;

    //======= USUARIO =========
    private CrearUsuarioView crearUsuarioView;
    private ActualizarUsuarioView actualizarUsuarioView;
    private EliminarUsuarioView eliminarUsuarioView;
    private BuscarUsuarioView buscarUsuarioView;
    private ListarUsuarioView listarUsuarioView;

    //======= PRESTAMO =========
    private CrearPrestamoView crearPrestamoView;
    private BuscarPrestamoView buscarPrestamoView;
    private ListarPrestamoView listarPrestamoView;
    private DevolucionPrestamoView devolucionPrestamoView;
    
    public PrincipalView() {
        initComponents();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        btnCrearLibro = new javax.swing.JMenuItem();
        btnActualizarLibro = new javax.swing.JMenuItem();
        btnEliminarLibro = new javax.swing.JMenuItem();
        btnListarLibro = new javax.swing.JMenuItem();
        btnBuscarLibro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnCrearUsuario = new javax.swing.JMenuItem();
        btnActualizarUsuario = new javax.swing.JMenuItem();
        btnEliminarUsuario = new javax.swing.JMenuItem();
        btnListarUsuario = new javax.swing.JMenuItem();
        btnBuscarUsuario = new javax.swing.JMenuItem();
        btnRegistro = new javax.swing.JMenu();
        btnCrearPrestamo = new javax.swing.JMenuItem();
        btnDevolucion = new javax.swing.JMenuItem();
        btnListarPrestamo = new javax.swing.JMenuItem();
        btnBuscarPrestamo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        desktopPane.add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 0, 400, 280);

        jMenu3.setText("Libros");

        btnCrearLibro.setText("Crear");
        btnCrearLibro.addActionListener(this::btnCrearLibroActionPerformed);
        jMenu3.add(btnCrearLibro);

        btnActualizarLibro.setText("Actualizar");
        btnActualizarLibro.addActionListener(this::btnActualizarLibroActionPerformed);
        jMenu3.add(btnActualizarLibro);

        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(this::btnEliminarLibroActionPerformed);
        jMenu3.add(btnEliminarLibro);

        btnListarLibro.setText("Listar");
        btnListarLibro.addActionListener(this::btnListarLibroActionPerformed);
        jMenu3.add(btnListarLibro);

        btnBuscarLibro.setText("Buscar");
        btnBuscarLibro.addActionListener(this::btnBuscarLibroActionPerformed);
        jMenu3.add(btnBuscarLibro);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Usuarios");

        btnCrearUsuario.setText("Crear");
        btnCrearUsuario.addActionListener(this::btnCrearUsuarioActionPerformed);
        jMenu4.add(btnCrearUsuario);

        btnActualizarUsuario.setText("Actualizar");
        btnActualizarUsuario.addActionListener(this::btnActualizarUsuarioActionPerformed);
        jMenu4.add(btnActualizarUsuario);

        btnEliminarUsuario.setText("Eliminar");
        btnEliminarUsuario.addActionListener(this::btnEliminarUsuarioActionPerformed);
        jMenu4.add(btnEliminarUsuario);

        btnListarUsuario.setText("Listar");
        btnListarUsuario.addActionListener(this::btnListarUsuarioActionPerformed);
        jMenu4.add(btnListarUsuario);

        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.addActionListener(this::btnBuscarUsuarioActionPerformed);
        jMenu4.add(btnBuscarUsuario);

        jMenuBar2.add(jMenu4);

        btnRegistro.setText("Registros");

        btnCrearPrestamo.setText("Registro");
        btnCrearPrestamo.addActionListener(this::btnCrearPrestamoActionPerformed);
        btnRegistro.add(btnCrearPrestamo);

        btnDevolucion.setText("Devolucion");
        btnDevolucion.setToolTipText("");
        btnDevolucion.addActionListener(this::btnDevolucionActionPerformed);
        btnRegistro.add(btnDevolucion);

        btnListarPrestamo.setText("Listar");
        btnListarPrestamo.addActionListener(this::btnListarPrestamoActionPerformed);
        btnRegistro.add(btnListarPrestamo);

        btnBuscarPrestamo.setText("Buscar");
        btnBuscarPrestamo.addActionListener(this::btnBuscarPrestamoActionPerformed);
        btnRegistro.add(btnBuscarPrestamo);

        jMenuBar2.add(btnRegistro);

        jMenu6.setText("Configuracion");

        jMenuItem17.setText("Español");
        jMenu6.add(jMenuItem17);

        jMenuItem16.setText("Ingles");
        jMenuItem16.addActionListener(this::jMenuItem16ActionPerformed);
        jMenu6.add(jMenuItem16);

        jMenuItem14.setText("jMenuItem14");
        jMenu6.add(jMenuItem14);

        jMenuItem15.setText("jMenuItem15");
        jMenu6.add(jMenuItem15);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarLibroActionPerformed
if(!listarLibroView.isVisible()) {
desktopPane.remove(listarLibroView);
listarLibroView.setVisible(true);
desktopPane.add(listarLibroView);
}
    }//GEN-LAST:event_btnListarLibroActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
if(!crearUsuarioView.isVisible()) {
desktopPane.remove(crearUsuarioView);
crearUsuarioView.setVisible(true);
desktopPane.add(crearUsuarioView);
}
    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarUsuarioActionPerformed
if(!actualizarUsuarioView.isVisible()) {
desktopPane.remove(actualizarUsuarioView);
actualizarUsuarioView.setVisible(true);
desktopPane.add(actualizarUsuarioView);
}
    }//GEN-LAST:event_btnActualizarUsuarioActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
if(!eliminarUsuarioView.isVisible()) {
desktopPane.remove(eliminarUsuarioView);
eliminarUsuarioView.setVisible(true);
desktopPane.add(eliminarUsuarioView);
}      
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    private void btnCrearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrestamoActionPerformed
if(!crearPrestamoView.isVisible()) {
desktopPane.remove(crearPrestamoView);
crearPrestamoView.setVisible(true);
desktopPane.add(crearPrestamoView);
} 
    }//GEN-LAST:event_btnCrearPrestamoActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroActionPerformed
if(!crearLibroView.isVisible()) {
desktopPane.remove(crearLibroView);
crearLibroView.setVisible(true);
desktopPane.add(crearLibroView);
}    
    }//GEN-LAST:event_btnCrearLibroActionPerformed

    private void btnActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroActionPerformed
if(!actualizarLibroView.isVisible()) {
desktopPane.remove(actualizarLibroView);
actualizarLibroView.setVisible(true);
desktopPane.add(actualizarLibroView);
}  
    }//GEN-LAST:event_btnActualizarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
if(!eliminarLibroView.isVisible()) {
desktopPane.remove(eliminarLibroView);
eliminarLibroView.setVisible(true);
desktopPane.add(eliminarLibroView);
}
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLibroActionPerformed
if(!buscarLibroView.isVisible()) {
desktopPane.remove(buscarLibroView);
buscarLibroView.setVisible(true);
desktopPane.add(buscarLibroView);
}
    }//GEN-LAST:event_btnBuscarLibroActionPerformed

    private void btnListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuarioActionPerformed
if(!listarUsuarioView.isVisible()) {
desktopPane.remove(listarUsuarioView);
listarUsuarioView.setVisible(true);
desktopPane.add(listarUsuarioView);
}  
    }//GEN-LAST:event_btnListarUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
if(!buscarUsuarioView.isVisible()) {
desktopPane.remove(buscarUsuarioView);
buscarUsuarioView.setVisible(true);
desktopPane.add(buscarUsuarioView);
} 
    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void btnDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolucionActionPerformed
if(!devolucionPrestamoView.isVisible()) {
desktopPane.remove(devolucionPrestamoView);
devolucionPrestamoView.setVisible(true);
desktopPane.add(devolucionPrestamoView);
} 
    }//GEN-LAST:event_btnDevolucionActionPerformed

    private void btnListarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPrestamoActionPerformed
if(!listarPrestamoView.isVisible()) {
desktopPane.remove(listarPrestamoView);
listarPrestamoView.setVisible(true);
desktopPane.add(listarPrestamoView);
} 
    }//GEN-LAST:event_btnListarPrestamoActionPerformed

    private void btnBuscarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPrestamoActionPerformed
if(!buscarPrestamoView.isVisible()) {
desktopPane.remove(buscarPrestamoView);
buscarPrestamoView.setVisible(true);
desktopPane.add(buscarPrestamoView);
}
    }//GEN-LAST:event_btnBuscarPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnActualizarLibro;
    private javax.swing.JMenuItem btnActualizarUsuario;
    private javax.swing.JMenuItem btnBuscarLibro;
    private javax.swing.JMenuItem btnBuscarPrestamo;
    private javax.swing.JMenuItem btnBuscarUsuario;
    private javax.swing.JMenuItem btnCrearLibro;
    private javax.swing.JMenuItem btnCrearPrestamo;
    private javax.swing.JMenuItem btnCrearUsuario;
    private javax.swing.JMenuItem btnDevolucion;
    private javax.swing.JMenuItem btnEliminarLibro;
    private javax.swing.JMenuItem btnEliminarUsuario;
    private javax.swing.JMenuItem btnListarLibro;
    private javax.swing.JMenuItem btnListarPrestamo;
    private javax.swing.JMenuItem btnListarUsuario;
    private javax.swing.JMenu btnRegistro;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    // End of variables declaration//GEN-END:variables

}
